// Deliberate structural guards. Each guard keeps a safety boundary that a behavior test cannot
// reach (workflow YAML or a forbidden raw API). Keep each guard small and give its reason.
import assert from "node:assert/strict";
import test from "node:test";
import { parse as parseYaml } from "yaml";

import { readText } from "./helpers.ts";

type Step = {
  id?: string;
  name?: string;
  uses?: string;
  if?: string;
  run?: string;
  env?: Record<string, string>;
  with?: Record<string, string>;
};
type Workflow = {
  jobs: Record<string, { steps?: Step[] }>;
};

function workflow(name: string): Workflow {
  return parseYaml(readText(`.github/workflows/${name}`)) as Workflow;
}

function steps(document: Workflow): Step[] {
  return Object.values(document.jobs).flatMap((job) => job.steps ?? []);
}

// test/repair source-text guards

// Cluster intake makes state durable and recovers pending dispatches before it selects new work.
test("cluster intake publishes jobs durably before dispatch", () => {
  const intake = workflow("repair-cluster-intake.yml").jobs.intake?.steps ?? [];
  const order = [
    intake.findIndex((step) => step.uses === "./.github/actions/create-state-token"),
    intake.findIndex((step) => step.uses === "./.github/actions/setup-state"),
    intake.findIndex((step) => step.name === "Recover pending cluster dispatches"),
    intake.findIndex((step) => step.name === "Prepare unprocessed cluster candidates"),
    intake.findIndex((step) => step.name === "Durably accept cluster intake"),
  ];
  assert.ok(order[0]! >= 0, "missing state token step");
  assert.deepEqual(
    order,
    [...order].sort((left, right) => left - right),
  );
});

// Post-flight records closure authorization only. Guarded apply owns every close.
test("post-flight never closes issues or pull requests", () => {
  assert.doesNotMatch(readText("src/repair/post-flight.ts"), /"close"|state: "closed"/);
});

// The selector model judges cluster quality. Code never ranks clusters with word lists or scores.
test("cluster selection has no semantic word lists, thresholds, or scores", () => {
  const sources = [
    "src/repair/select-cluster-candidate.ts",
    "src/repair/import-gitcrawl-clusters.ts",
  ]
    .map(readText)
    .join("\n");
  assert.doesNotMatch(sources, /_WORDS\b|DECISION_LABELS|FEATURE_LABELS|BUG_LABELS/);
  assert.doesNotMatch(sources, /selection score|title cohesion|closedPercent|maxAgeDays/);
});

// A generated issue PR carries the autogenerated label that every merge gate refuses.
// The executor has no seam to open a PR in a test.
test("generated issue implementation PRs never enter automerge", () => {
  assert.match(
    readText("src/repair/execute-fix-artifact.ts"),
    /source === "issue_implementation"\) \{[^}]*addLabel\(result\.repo, number, AUTOGENERATED_LABEL[^}]*removeLabelIfPresent\(result\.repo, number, AUTOMERGE_LABEL/,
  );
  // R7RouterCore's readiness behavior test replaces this router check when it moves to core.
  assert.match(
    ["src/repair/comment-router.ts", "src/repair/comment-router-core.ts"].map(readText).join("\n"),
    /AUTOGENERATED_LABEL\)\)\s*return "generated issue implementation PRs require manual merge"/,
  );
});

// Repair target read tokens cover only the validated target, never a fixed repository.
test("repair target read tokens are scoped to the resolved target", () => {
  const intake = steps(workflow("repair-cluster-intake.yml")).find(
    (step) => step.name === "Create target read token",
  );
  assert.equal(intake?.with?.owner, "${{ steps.target.outputs.owner }}");
  assert.equal(intake?.with?.repositories, "${{ steps.target.outputs.name }}");
  const publish = steps(workflow("repair-publish-results.yml"));
  const reader = publish.find((step) => step.name === "Create target read token");
  assert.equal(reader?.with?.owner, "${{ steps.result-targets.outputs.owner }}");
  assert.equal(reader?.with?.repositories, "${{ steps.result-targets.outputs.repositories }}");
  // Result publication writes state with the state credential, never with an app token.
  for (const step of publish) assert.notEqual(step.with?.["permission-contents"], "write");
});

// review-prompt-context.test.ts guards

// Product-direction closes act on contributor items. The workflow must keep them off unless a
// maintainer sets the repository variable.
test("sweep workflow keeps the product-direction close gate off by default", () => {
  type Env = Record<string, string> | undefined;
  const workflow = parseYaml(readText(".github/workflows/sweep.yml")) as {
    env?: Env;
    jobs: Record<string, { env?: Env; steps?: Array<{ env?: Env }> }>;
  };
  const values = [
    workflow.env,
    ...Object.values(workflow.jobs).flatMap((job) => [
      job.env,
      ...(job.steps ?? []).map((step) => step.env),
    ]),
  ].flatMap((env) => env?.CLAWSWEEPER_UNCONFIRMED_PRODUCT_DIRECTION_CLOSE_ENABLED ?? []);
  assert.ok(values.length > 0);
  for (const value of values) {
    assert.equal(
      value,
      "${{ vars.CLAWSWEEPER_UNCONFIRMED_PRODUCT_DIRECTION_CLOSE_ENABLED || 'false' }}",
    );
  }
});
