// Deliberate structural guards. Each guard keeps a safety boundary that a behavior test cannot
// reach (workflow YAML or a forbidden raw API). Keep each guard small and give its reason.
import assert from "node:assert/strict";
import { globSync, readdirSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { parse as parseYaml } from "yaml";

import { readText } from "./helpers.ts";

type Step = {
  id?: string;
  name?: string;
  uses?: string;
  if?: string;
  run?: string;
  env?: Record<string, string>;
  with?: Record<string, string>;
  "continue-on-error"?: unknown;
};
type Workflow = {
  env?: Record<string, string>;
  concurrency?: { group: string; "cancel-in-progress": boolean };
  on: {
    workflow_dispatch?: { inputs: Record<string, { default?: string }> };
    push?: { paths?: string[] } | null;
    pull_request?: { paths?: string[] } | null;
  };
  permissions?: unknown;
  jobs: Record<
    string,
    { if?: string; env?: Record<string, string>; "continue-on-error"?: unknown; steps?: Step[] }
  >;
};

function workflow(name: string): Workflow {
  return parseYaml(readText(`.github/workflows/${name}`)) as Workflow;
}

function steps(document: Workflow): Step[] {
  return Object.values(document.jobs).flatMap((job) => job.steps ?? []);
}

// test/repair source-text guards

// Cluster intake makes state durable and recovers pending dispatches before it selects new work.
test("cluster intake publishes jobs durably before dispatch", () => {
  const intake = workflow("repair-cluster-intake.yml").jobs.intake?.steps ?? [];
  const order = [
    intake.findIndex((step) => step.uses === "./.github/actions/create-state-token"),
    intake.findIndex((step) => step.uses === "./.github/actions/setup-state"),
    intake.findIndex((step) => step.name === "Recover pending cluster dispatches"),
    intake.findIndex((step) => step.name === "Prepare unprocessed cluster candidates"),
    intake.findIndex((step) => step.name === "Durably accept cluster intake"),
  ];
  assert.ok(order[0]! >= 0, "missing state token step");
  assert.deepEqual(
    order,
    [...order].sort((left, right) => left - right),
  );
});

// Post-flight records closure authorization only. Guarded apply owns every close.
test("post-flight never closes issues or pull requests", () => {
  assert.doesNotMatch(readText("src/repair/post-flight.ts"), /"close"|state: "closed"/);
});

// The selector model judges cluster quality. Code never ranks clusters with word lists or scores.
test("cluster selection has no semantic word lists, thresholds, or scores", () => {
  const sources = [
    "src/repair/select-cluster-candidate.ts",
    "src/repair/import-gitcrawl-clusters.ts",
  ]
    .map(readText)
    .join("\n");
  assert.doesNotMatch(sources, /_WORDS\b|DECISION_LABELS|FEATURE_LABELS|BUG_LABELS/);
  assert.doesNotMatch(sources, /selection score|title cohesion|closedPercent|maxAgeDays/);
});

// A generated issue PR carries the autogenerated label that every merge gate refuses.
// The executor has no seam to open a PR in a test.
test("generated issue implementation PRs never enter automerge", () => {
  assert.match(
    readText("src/repair/execute-fix-artifact.ts"),
    /source === "issue_implementation"\) \{[^}]*addLabel\(result\.repo, number, AUTOGENERATED_LABEL[^}]*removeLabelIfPresent\(result\.repo, number, AUTOMERGE_LABEL/,
  );
  // R7RouterCore's readiness behavior test replaces this router check when it moves to core.
  assert.match(
    ["src/repair/comment-router.ts", "src/repair/comment-router-core.ts"].map(readText).join("\n"),
    /AUTOGENERATED_LABEL\)\)\s*return "generated issue implementation PRs require manual merge"/,
  );
});

// Repair target read tokens cover only the validated target, never a fixed repository.
test("repair target read tokens are scoped to the resolved target", () => {
  const intake = steps(workflow("repair-cluster-intake.yml")).find(
    (step) => step.name === "Create target read token",
  );
  assert.equal(intake?.with?.owner, "${{ steps.target.outputs.owner }}");
  assert.equal(intake?.with?.repositories, "${{ steps.target.outputs.name }}");
  const publish = steps(workflow("repair-publish-results.yml"));
  const reader = publish.find((step) => step.name === "Create target read token");
  assert.equal(reader?.with?.owner, "${{ steps.result-targets.outputs.owner }}");
  assert.equal(reader?.with?.repositories, "${{ steps.result-targets.outputs.repositories }}");
  // Result publication writes state with the state credential, never with an app token.
  for (const step of publish) assert.notEqual(step.with?.["permission-contents"], "write");
});

// review-prompt-context.test.ts guards

// Product-direction closes act on contributor items. The workflow must keep them off unless a
// maintainer sets the repository variable.
test("sweep workflow keeps the product-direction close gate off by default", () => {
  type Env = Record<string, string> | undefined;
  const workflow = parseYaml(readText(".github/workflows/sweep.yml")) as {
    env?: Env;
    jobs: Record<string, { env?: Env; steps?: Array<{ env?: Env }> }>;
  };
  const values = [
    workflow.env,
    ...Object.values(workflow.jobs).flatMap((job) => [
      job.env,
      ...(job.steps ?? []).map((step) => step.env),
    ]),
  ].flatMap((env) => env?.CLAWSWEEPER_UNCONFIRMED_PRODUCT_DIRECTION_CLOSE_ENABLED ?? []);
  assert.ok(values.length > 0);
  for (const value of values) {
    assert.equal(
      value,
      "${{ vars.CLAWSWEEPER_UNCONFIRMED_PRODUCT_DIRECTION_CLOSE_ENABLED || 'false' }}",
    );
  }
});

// clawsweeper.test.ts workflow and source guards

// Duplicate deliveries of one comment cancel each other; other comments never do.
test("spam comment intake cancels only duplicate deliveries of the same comment", () => {
  const concurrency = workflow("spam-comment-intake.yml").concurrency;
  assert.equal(concurrency?.["cancel-in-progress"], true);
  for (const key of ["comment_id", "review_comment_id", "activity.comment.id"]) {
    assert.ok(concurrency?.group.includes(`client_payload.${key}`), key);
  }
});

// Exact spam scans run per comment and never cancel one another.
test("spam scanner exact dispatches never cancel other scans", () => {
  const concurrency = workflow("spam-scanner.yml").concurrency;
  assert.equal(concurrency?.["cancel-in-progress"], false);
  assert.ok(concurrency?.group.includes("spam-scanner-{0}-issue-comment-{1}"));
  assert.ok(concurrency?.group.includes("spam-scanner-{0}-review-comment-{1}"));
});

// A requeue dispatch needs a durable ledger, and session reports follow the dispatch outcome.
test("repair worker requeue dispatch waits for its durable ledger", () => {
  const all = steps(workflow("repair-cluster-worker.yml"));
  const dispatch = all.find((step) => step.id === "requeue_dispatch");
  assert.match(dispatch?.if ?? "", /steps\.repair-requeue-ledger\.outcome == 'success'/);
  const failure = all.find((step) => step.name === "Record work failure");
  assert.match(failure?.if ?? "", /steps\.requeue_dispatch\.outcome != 'success'/);
});

// Agent CLIs install exact releases, never a moving tag; OpenClaw source builds stay opt-in.
test("agent CLI setup actions install exact pinned releases", () => {
  const exact = /^\d+\.\d+\.\d+$/;
  for (const [action, inputs] of [
    ["setup-codex", ["codex-version", "proxy-version"]],
    ["setup-openclaw", ["openclaw-version"]],
  ] as const) {
    const document = parseYaml(readText(`.github/actions/${action}/action.yml`)) as {
      inputs: Record<string, { default?: string }>;
      runs: { steps: Step[] };
    };
    for (const input of inputs) assert.match(document.inputs[input]?.default ?? "", exact, input);
    for (const step of document.runs.steps) assert.doesNotMatch(step.run ?? "", /@latest/);
    if (action === "setup-openclaw") {
      assert.equal(document.inputs["openclaw-source-ref"]?.default, "");
      for (const step of document.runs.steps) {
        assert.match(step.if ?? "", /env\.CLAWSWEEPER_RUNNER == 'openclaw'/);
      }
    }
  }
});

// Model credentials stay in step env, so setup steps and other steps never inherit them.
test("workflows never expose model credentials at workflow or job scope", () => {
  for (const name of readdirSync(".github/workflows").filter((file) => file.endsWith(".yml"))) {
    const document = workflow(name);
    for (const env of [document.env, ...Object.values(document.jobs).map((job) => job.env)]) {
      for (const secret of ["OPENAI_API_KEY", "CLAWSWEEPER_INTERNAL_MODEL"]) {
        assert.equal(Object.hasOwn(env ?? {}, secret), false, `${name}: ${secret}`);
      }
    }
  }
});

// Repair planning stays read-only unless an operator picks the trusted-runner fallback.
test("repair worker planner sandbox defaults to read-only", () => {
  const input = workflow("repair-cluster-worker.yml").on.workflow_dispatch?.inputs.planner_sandbox;
  assert.equal(input?.default, "read-only");
});

// Scheduled cluster intake is gated at job level, before any credential is created.
test("scheduled cluster intake is gated before it creates credentials", () => {
  const intake = workflow("repair-cluster-intake.yml").jobs.intake;
  assert.equal(
    intake?.if,
    "${{ github.event_name != 'schedule' || vars.CLAWSWEEPER_FEATURE_CLUSTER_REPAIR_ENABLED == '1' }}",
  );
});

// Cluster intake dispatches workers only through the durable intake publisher.
test("cluster intake never dispatches workers before durable acceptance", () => {
  for (const step of steps(workflow("repair-cluster-intake.yml"))) {
    assert.doesNotMatch(step.run ?? "", /repair:dispatch\b|state-materializer\.yml/, step.name);
  }
});

// A self-heal worker can hydrate its exact-head job only after the job is published.
test("conflict self-heal publishes jobs before it dispatches workers", () => {
  const source = readText("src/repair/conflict-self-heal.ts");
  const publish = source.indexOf("publishSelfHealJobs();");
  assert.ok(publish >= 0);
  assert.ok(source.indexOf("dispatchRepair(candidate);") > publish);
});

// Terminal acknowledgements write comments and labels only, never repository content.
test("terminal finalization target token cannot write repository content", () => {
  const tokens = workflow("sweep.yml").jobs["event-review-terminal-finalization"]?.steps?.filter(
    (step) => step.id === "target-write-token",
  );
  assert.equal(tokens?.length, 1);
  assert.notEqual(tokens?.[0]?.with?.["permission-contents"], "write");
});

// Automatic failed-review recovery and record-only manual reviews publish review comments only.
test("automatic retry publication remains review-only", () => {
  const reviewOnly = steps(workflow("sweep.yml")).find(
    (step) => step.id === "prepare-direct-exact-review-publication",
  )?.env?.REVIEW_ONLY;
  assert.equal(typeof reviewOnly, "string");
  for (const [sourceAction, publicationPolicy, expected] of [
    ["failed_review_shard_recovery", "", "true"],
    ["manual_explicit_review", "record_comment_only", "true"],
    ["command_proof_result", "", "false"],
    ["opened", "", "false"],
    ["source_drift_requeue", "", "false"],
  ]) {
    const expression = reviewOnly!
      .replace(/^\$\{\{\s*|\s*\}\}$/g, "")
      .replace(
        "fromJSON(steps.claim-exact-review-queue.outputs.decision).sourceAction",
        JSON.stringify(sourceAction),
      )
      .replace(
        "fromJSON(steps.claim-exact-review-queue.outputs.decision).publicationPolicy",
        JSON.stringify(publicationPolicy),
      );
    const contains = (values: string[], value: string) => values.includes(value);
    assert.equal(
      Function("contains", "fromJSON", `return (${expression});`)(contains, JSON.parse),
      expected,
      sourceAction,
    );
  }
});

// Failed-review retries plan only until an operator enables live dispatch.
test("failed-review retries default to dry-run", () => {
  const retry = workflow("sweep.yml").jobs["retry-failed-reviews"]?.steps?.find(
    (step) => step.env?.DRY_RUN !== undefined,
  );
  assert.equal(
    retry?.env?.DRY_RUN,
    "${{ vars.CLAWSWEEPER_FAILED_REVIEW_RETRY_ENABLED == '1' && 'false' || 'true' }}",
  );
});

// Status publication names its target repository, so it never writes another repository.
test("sweep status writes are scoped to the target repository", () => {
  const statusSteps = steps(workflow("sweep.yml")).filter((step) =>
    step.run?.includes("pnpm run status --"),
  );
  assert.ok(statusSteps.length > 0);
  for (const step of statusSteps) assert.match(step.run ?? "", /--target-repo /, step.name);
});

// execute-fix-artifact-source.test.ts guards

// A direct Codex launch skips the agent runner sandbox, input scan, timeout and file capture.
// This guard also replaces the clawsweeper.test.ts review-surface check.
test("production code launches Codex only through the agent runner", () => {
  const directLaunch = /\b(?:spawn|spawnSync|execFile|execFileSync)\(\s*["'`]codex["'`]/;
  const offenders = globSync("src/**/*.ts").filter((file) => {
    const source = readText(file);
    const runnerFile =
      file === join("src", "agent-runner.ts") || file === join("src", "codex-process.ts");
    return directLaunch.test(source) || (!runnerFile && /\brunCodexProcess\b/.test(source));
  });
  assert.deepEqual(offenders, []);
});

// test/repair containment and E2E workflow guards

// Linux behavior tests skip on runners without delegated namespaces, so pin the namespace set.
test("validation worker enters fresh user, mount, PID and network namespaces", () => {
  const worker = readText("src/repair/contained-command-worker.ts");
  for (const flag of [
    "--user",
    "--map-root-user",
    "--mount",
    "--pid",
    "--fork",
    "--mount-proc",
    "--kill-child=SIGKILL",
  ]) {
    assert.ok(worker.includes(`"${flag}"`), flag);
  }
  assert.match(worker, /input\.isolateNetwork \? \["--net"\] : \[\]/);
});

// Fix execution runs target code, so the containment preflight must pass first under the same gate.
test("containment preflight gates every fix execution", () => {
  const steps = workflow("repair-cluster-worker.yml").jobs.execute!.steps ?? [];
  const preflight = steps.findIndex((step) => step.run === "pnpm run repair:containment-smoke");
  const execute = steps.findIndex((step) => step.name === "Execute credited fix artifact");
  assert.ok(preflight >= 0 && preflight < execute);
  assert.equal(steps[preflight]!.if, steps[execute]!.if);
  assert.equal(steps[preflight]!["continue-on-error"], undefined);
});

// A plan-only or unauthorized planning run must never reach the execute job.
test("execute job runs only after allowed execute or autonomous planning", () => {
  const condition = workflow("repair-cluster-worker.yml").jobs.execute!.if ?? "";
  assert.ok(condition.includes("needs.cluster.outputs.allow_execute == '1'"));
  assert.ok(
    condition.includes(
      "(needs.cluster.outputs.effective_mode == 'execute' || needs.cluster.outputs.effective_mode == 'autonomous')",
    ),
  );
});

// The smoke is the only pre-merge run of real containment on a production-class runner.
test("containment smoke runs the compiled preflight for every containment change", () => {
  const document = workflow("repair-containment-smoke.yml");
  const job = document.jobs["containment-smoke"]!;
  const jobSteps = job.steps ?? [];
  assert.deepEqual(
    jobSteps.filter((step) => step.run).map((step) => step.run),
    ["pnpm run repair:containment-smoke"],
  );
  assert.ok(jobSteps.every((step) => step["continue-on-error"] === undefined));
  assert.equal(job["continue-on-error"], undefined);
  for (const source of [
    "src/repair/contained-command-sandbox.ts",
    "src/repair/contained-command-worker.ts",
    "src/repair/containment-preflight.ts",
    "src/repair/process-tree-containment.ts",
  ]) {
    assert.ok(document.on.push?.paths?.includes(source), source);
    assert.ok(document.on.pull_request?.paths?.includes(source), source);
  }
});

// E2E workflows run repository code on shared runners and must never hold write tokens or secrets.
test("E2E workflows are read-only and skip fork pull requests", () => {
  for (const name of ["automerge-e2e.yml", "repair-containment-smoke.yml"]) {
    const document = workflow(name);
    assert.deepEqual(document.permissions, { contents: "read" }, name);
    for (const job of Object.values(document.jobs)) {
      assert.match(
        job.if ?? "",
        /github\.event\.pull_request\.head\.repo\.full_name == github\.repository/,
      );
      const checkout = job.steps?.find((step) => step.uses?.startsWith("actions/checkout@"));
      assert.equal(checkout?.with?.["persist-credentials"], false, name);
    }
    assert.doesNotMatch(readText(`.github/workflows/${name}`), /secrets\.|GH_TOKEN|app-token/);
  }
});

// The automerge E2E image must come from repository source, not from a registry or a stale cache.
test("automerge E2E builds its base image from the repository Dockerfile", () => {
  const job = workflow("automerge-e2e.yml").jobs["automerge-e2e"]!;
  assert.doesNotMatch(job.env?.AUTOMERGE_E2E_BASE_IMAGE ?? "", /\//);
  const cache = job.steps?.find((step) => step.uses?.startsWith("actions/cache@"));
  assert.match(String(cache?.with?.key), /hashFiles\('test\/e2e\/automerge\/Dockerfile\.base'\)/);
  const runs = (job.steps ?? []).map((step) => step.run ?? "").join("\n");
  assert.match(runs, /docker build \\\n\s+--file test\/e2e\/automerge\/Dockerfile\.base/);
  assert.doesNotMatch(runs, /docker pull/);
});
