import type {
  PolicyProposalJson,
  ScoredPolicyPattern,
  SynthesizeOptions,
  SynthesizedPolicyProposal,
} from "./types.js";

export function synthesizePolicyProposal(
  pattern: ScoredPolicyPattern,
  options: SynthesizeOptions = {},
): SynthesizedPolicyProposal {
  const createdAt = options.createdAt ?? new Date().toISOString();
  const json = policyProposalJson(pattern, createdAt);
  return {
    id: pattern.id,
    markdown: policyProposalMarkdown(pattern, createdAt),
    json,
  };
}

export function policyProposalJson(
  pattern: ScoredPolicyPattern,
  createdAt: string,
): PolicyProposalJson {
  return {
    id: pattern.id,
    title: pattern.title,
    status: "Draft",
    pattern_type: pattern.patternType,
    evidence_items: pattern.evidenceItems.map((item) => {
      const evidence = {
        repo: item.repo,
        item: item.item,
        source_record: item.sourceRecord,
      };
      return {
        ...evidence,
        ...(item.observedAt ? { observed_at: item.observedAt } : {}),
        ...(item.detail ? { detail: item.detail } : {}),
      };
    }),
    confidence_score: pattern.confidenceScore,
    proposed_conditions: pattern.proposedConditions,
    proposed_action: pattern.proposedAction,
    safety_constraints: pattern.safetyConstraints,
    created_at: createdAt,
    source_records: pattern.sourceRecords,
  };
}

export function policyProposalMarkdown(pattern: ScoredPolicyPattern, createdAt: string): string {
  return [
    `# ${pattern.title}`,
    "",
    "Status: Draft",
    "",
    "## Summary",
    "",
    `ClawSweeper observed the repeated \`${pattern.patternType}\` pattern \`${pattern.value}\` across ${pattern.occurrenceCount} records. This RFC proposes documenting a conservative policy candidate for maintainer review only.`,
    "",
    "## Observed Pattern",
    "",
    `- Pattern type: \`${pattern.patternType}\``,
    `- Pattern value: \`${pattern.value}\``,
    `- Occurrences: ${pattern.occurrenceCount}`,
    `- Distinct items: ${pattern.distinctItems.length}`,
    `- Distinct repositories: ${pattern.distinctRepos.length}`,
    `- Successful repair/apply outcomes observed: ${pattern.successfulOutcomes}`,
    `- Latest observation: ${pattern.latestObservedAt ?? "unknown"}`,
    `- Confidence score: ${pattern.confidenceScore.toFixed(3)}`,
    "",
    "## Evidence",
    "",
    ...evidenceLines(pattern),
    "",
    "## Proposed Policy",
    "",
    pattern.proposedAction,
    "",
    "Proposed conditions:",
    "",
    ...pattern.proposedConditions.map((condition) => `- ${condition}`),
    "",
    "## Safety Constraints",
    "",
    ...pattern.safetyConstraints.map((constraint) => `- ${constraint}`),
    "",
    "## Non-Goals",
    "",
    "- Do not auto-apply this policy.",
    "- Do not mutate GitHub state from this proposal.",
    "- Do not alter scheduler cadence, review shards, close behavior, apply behavior, or automerge behavior.",
    "",
    "## Rollout Plan",
    "",
    "1. Review this RFC with maintainers.",
    "2. If accepted, convert the proposal into an explicit policy change in a separate pull request.",
    "3. Ship any executable behavior behind existing conservative apply paths and tests.",
    "",
    "## Metrics",
    "",
    "- Number of future records matching the proposed conditions.",
    "- False-positive rate found during maintainer review.",
    "- Number of accepted, revised, or rejected proposals for this pattern.",
    "",
    "## Reversion Plan",
    "",
    "Archive or delete the generated RFC and JSON proposal. Since this engine is proposal-only, no runtime policy behavior needs to be reverted.",
    "",
    `Generated by ClawSweeper Policy RFC Engine at ${createdAt}.`,
    "",
  ].join("\n");
}

function evidenceLines(pattern: ScoredPolicyPattern): string[] {
  if (!pattern.evidenceItems.length) return ["No evidence items were retained."];
  return pattern.evidenceItems.map((item) => {
    const observed = item.observedAt ? ` observed ${item.observedAt}` : "";
    return `- ${item.repo} ${item.item}${observed}: \`${item.sourceRecord}\``;
  });
}
