import type { Item } from "./clawsweeper-types.js";
import {
  canPatchReviewComment,
  isCodexReviewCommentBody,
  shouldPreserveReviewStartLease,
  withReviewStartStatusLease,
  renderReviewStartStatusComment,
  fetchIssueReviewComments,
  issueReviewCommentState,
  commentId,
  commentBody,
  PATCHABLE_REVIEW_COMMENT_AUTHORS,
  staleReviewCommentSyncReason,
  newerDurableReviewTupleVerified,
  reviewCommentHasCloseVerdictForCanonical,
  issueReviewComment,
  markedReviewCommentBody,
  commentBodyMatches,
  reviewCommentHashMatches,
  commentUpdatedAt,
} from "./clawsweeper-review-comment-state.js";
import {
  writeCommentPayload,
  coverageProofRetryExhaustedRuntimeBudget,
  recordedLabelSyncCoversUpdate,
  removeCurrentCursorTraceItem,
  reviewArtifactDestination,
  runtimeBudgetExceeded,
  timeoutWithinRuntimeBudget,
  updateReviewCommentMetadata,
  upsertReviewComment,
  ensureCloseAppliedComment,
} from "./clawsweeper-review-comment-publication.js";
import {
  reviewStartLeaseOwner,
  exactReviewQueueAuthorityFromEnv,
  postReviewStartStatusComment,
  deleteOwnedDedicatedReviewStartLease,
  freshDedicatedReviewStartLeases,
} from "./clawsweeper-review-comment-leases.js";

export function createReviewCommentWorkflow(readLiveReviewRevision: (item: Item) => string) {
  return {
    canPatchReviewComment,
    coverageProofRetryExhaustedRuntimeBudget,
    isCodexReviewCommentBody,
    recordedLabelSyncCoversUpdate,
    removeCurrentCursorTraceItem,
    renderReviewStartStatusComment,
    reviewArtifactDestination,
    runtimeBudgetExceeded,
    shouldPreserveReviewStartLease,
    timeoutWithinRuntimeBudget,
    withReviewStartStatusLease,
    commentId,
    fetchIssueReviewComments,
    writeCommentPayload,
    exactReviewQueueAuthorityFromEnv,
    postReviewStartStatusComment: (options: Parameters<typeof postReviewStartStatusComment>[0]) =>
      postReviewStartStatusComment(options, readLiveReviewRevision),
    deleteOwnedDedicatedReviewStartLease,
    freshDedicatedReviewStartLeases,
    issueReviewCommentState,
    PATCHABLE_REVIEW_COMMENT_AUTHORS,
    staleReviewCommentSyncReason,
    newerDurableReviewTupleVerified,
    reviewCommentHasCloseVerdictForCanonical,
    issueReviewComment,
    markedReviewCommentBody,
    commentBodyMatches,
    reviewCommentHashMatches,
    commentUpdatedAt,
    reviewStartLeaseOwner,
    commentBody,
    updateReviewCommentMetadata,
    upsertReviewComment,
    ensureCloseAppliedComment,
  };
}
