import type { CreateReportOrchestrationDependencies } from "./clawsweeper-report-orchestration-dependencies.js";
import { createReportRendering } from "./clawsweeper-report-rendering.js";
import { createReportOrchestrationFoundation } from "./clawsweeper-orchestration-foundation.js";
import { createPullRequestPromotionFacts } from "./clawsweeper-promotion-facts.js";
import { createPullRequestCoverageProof } from "./clawsweeper-coverage-proof.js";
import { createPullRequestClosePromotion } from "./clawsweeper-close-promotion.js";
import { createReportLabelPresentation } from "./clawsweeper-label-presentation.js";

export function createReportOrchestration(dependencies: CreateReportOrchestrationDependencies) {
  let reportRendering: ReturnType<typeof createReportRendering>;
  const renderingReferences = {
    collapsedDetailsBlock: (
      ...args: Parameters<ReturnType<typeof createReportRendering>["collapsedDetailsBlock"]>
    ) => reportRendering.collapsedDetailsBlock(...args),
    renderCloseCommentFromReport: (
      ...args: Parameters<ReturnType<typeof createReportRendering>["renderCloseCommentFromReport"]>
    ) => reportRendering.renderCloseCommentFromReport(...args),
    renderPrRatingAssessmentReportSection: (
      ...args: Parameters<
        ReturnType<typeof createReportRendering>["renderPrRatingAssessmentReportSection"]
      >
    ) => reportRendering.renderPrRatingAssessmentReportSection(...args),
    renderRootCauseClusterAssessmentReportSection: (
      ...args: Parameters<
        ReturnType<typeof createReportRendering>["renderRootCauseClusterAssessmentReportSection"]
      >
    ) => reportRendering.renderRootCauseClusterAssessmentReportSection(...args),
  };
  const orchestrationFoundation = createReportOrchestrationFoundation({
    ...dependencies,
    ...renderingReferences,
  });
  const promotionFacts = createPullRequestPromotionFacts({
    ...dependencies,
    ...renderingReferences,
    ...orchestrationFoundation,
  });
  const coverageProof = createPullRequestCoverageProof({
    ...dependencies,
    ...renderingReferences,
    ...orchestrationFoundation,
    ...promotionFacts,
  });
  const closePromotion = createPullRequestClosePromotion({
    ...dependencies,
    ...renderingReferences,
    ...orchestrationFoundation,
    ...promotionFacts,
    ...coverageProof,
  });
  const labelPresentation = createReportLabelPresentation({
    ...dependencies,
    ...renderingReferences,
    ...orchestrationFoundation,
  });
  const {
    agentsPolicyStatusLine,
    closeEvidenceLine,
    collectItemContext,
    compactPullFilePaths,
    confidenceText,
    ensureDir,
    fileUrl,
    normalizeEvidence,
    fixedInReportText,
    fixedInText,
    fixedPullRequestFromReport,
    regressionAssessmentFromReport,
    regressionProvenanceFromReport,
    formatReviewFreshnessTimestamp,
    formatTimestamp,
    frontMatterStringArray,
    frontMatterValue,
    ghJson,
    ghObservedMutationCommand,
    hasUsableCloseComment,
    isImplementationCloseReason,
    isMaintainerAuthored,
    isReportNoneList,
    isVerifiedFixedCloseReason,
    jsonFrontMatterValue,
    likelyOwnerLines,
    linkedRelease,
    linkedSha,
    markdownLink,
    markdownRepository,
    mergeRiskOptionsFromReport,
    neutralizeOwnedSectionSpoofing,
    normalizePublicReviewText,
    priorityLabel,
    publicFailedReviewReadinessBlock,
    publicHistoricalVerificationBlockerLine,
    publicMergeReadinessBlock,
    publicRankScaleLine,
    publicRealBehaviorProofLine,
    publicReviewScoresBlock,
    publicReviewTextDiffers,
    publicReviewTextIsSame,
    publicRiskBullets,
    publicSecurityReviewLine,
    pullHeadShaFromContext,
    pullHeadShaFromReport,
    repairLoopPassModeFromReport,
    replaceFrontMatterValue,
    repoRelativePath,
    reportAgentsPolicyStatus,
    reportEvidence,
    reportLikelyOwners,
    reportLiveProofRecordingBlock,
    reportOverallConfidenceScore,
    reportOverallCorrectness,
    reportPrRating,
    reportRealBehaviorProofPolicy,
    reportReviewFindings,
    reportRootCauseCluster,
    reportRiskEntries,
    reportSecurityReview,
    reviewAutomationMarkersFromReport,
    reviewFindingDetailedLine,
    reviewFindingLocation,
    reviewFindingSummaryLine,
    reviewSectionValue,
    reviewStructuralPullStateFromContext,
    reviewVersionMarkerFromReport,
    ROOT,
    sanitizeArchitectureDiagram,
    securityConcernDetailedLine,
    securityConcernLocation,
    securityConcernSummaryLine,
    securityReviewLine,
    sentence,
    sha256,
    stripListMarker,
    targetRepo,
    timestampMs,
    triagePriorityFromReport,
    validateCloseDecision,
    workStatusForDecision,
  } = dependencies;
  const {
    closeIntro,
    closeOutro,
    closeClawHubHandoffBlock,
    duplicateCanonicalLinks,
    duplicateCanonicalPathLine,
    prSurfaceFilesFromContext,
    renderOpenClawPrSurfaceFromReport,
    reviewMetricsFromReport,
    renderReviewMetricsDigest,
    labelSynchronization,
    impactLabelSchemeForTest,
    impactLabelsForTest,
    isGitHubLabelAlreadyExistsErrorForTest,
    isGitHubLabelCapacityErrorForTest,
    isMissingGitHubLabelErrorForTest,
    issueAdvisoryLabelsForTest,
    maturityLabelSchemeForTest,
    maturityLabelsForTest,
    mergeRiskLabelSchemeForTest,
    mergeRiskLabelsForTest,
    priorityLabelSchemeForTest,
    priorityLabelsForTest,
    prRatingLabelSchemeForTest,
    prRatingLabelsForTest,
    realBehaviorProofMediaLabelsForTest,
    realBehaviorProofSufficientLabelsForTest,
    syncBulkFilerLabelForTest,
    telegramVisibleProofLabelsForTest,
    realBehaviorProofBlocksMerge,
    normalizedLabelSet,
    hasNormalizedLabel,
    parseBacktickLocation,
    workCandidateReasonText,
    reportDecision,
    livePullRequestHasNoDiff,
    upgradeNoDiffPullRequestReport,
    upgradePullRequestClosePromotionReport,
    authorPrBudgetPromotion,
    applyAuthorPrBudgetStateToReport,
    contextHasNonAutomationActivityAfter,
    contextHasNonAutomationActivityAfterForTest,
    duplicateCanonicalPullRequestBlockReason,
    canonicalPullRequestCommentSyncBlock,
    coveringPrCloseCoveragePullRequestSnapshotSha256,
    prCloseCoverageProofGateResult,
    applyPrCloseCoverageProofReportSection,
    applyPrCloseCoverageProofBlockedReport,
    applyClosedUnmergedCanonicalBlockedReport,
    staleCanonicalCommentSyncPendingReason,
    staleCanonicalPullRequestNumber,
    completeStaleCanonicalCommentSyncReport,
    pullRequestClosePromotion,
    workPlanPathForReport,
    shouldRenderWorkPlanFromReport,
    formattedMarkdownList,
    labelJustificationsMarkdown,
    labelTransitionJustificationsMarkdown,
    labelJustificationsMarkdownForTest,
    isClawSweeperOwnedLabel,
    labelTransitionJustificationsFromPublicReport,
    labelJustificationsFromPublicReport,
    inlineCode,
  } = {
    ...orchestrationFoundation,
    ...promotionFacts,
    ...coverageProof,
    ...closePromotion,
    ...labelPresentation,
  };

  reportRendering = createReportRendering({
    agentsPolicyStatusLine,
    closeClawHubHandoffBlock,
    closeEvidenceLine,
    closeIntro,
    closeOutro,
    collectItemContext,
    compactPullFilePaths,
    confidenceText,
    duplicateCanonicalLinks,
    duplicateCanonicalPathLine,
    ensureDir,
    fileUrl,
    normalizeEvidence,
    fixedInReportText,
    fixedInText,
    fixedPullRequestFromReport,
    regressionAssessmentFromReport,
    regressionProvenanceFromReport,
    formatReviewFreshnessTimestamp,
    formattedMarkdownList,
    formatTimestamp,
    frontMatterStringArray,
    frontMatterValue,
    ghJson,
    ghObservedMutationCommand,
    hasUsableCloseComment,
    inlineCode,
    isImplementationCloseReason,
    isMaintainerAuthored,
    isReportNoneList,
    isVerifiedFixedCloseReason,
    jsonFrontMatterValue,
    labelJustificationsFromPublicReport,
    labelJustificationsMarkdown,
    labelTransitionJustificationsFromPublicReport,
    labelTransitionJustificationsMarkdown,
    likelyOwnerLines,
    linkedRelease,
    linkedSha,
    markdownLink,
    markdownRepository,
    mergeRiskOptionsFromReport,
    neutralizeOwnedSectionSpoofing,
    normalizePublicReviewText,
    priorityLabel,
    prSurfaceFilesFromContext,
    publicFailedReviewReadinessBlock,
    publicHistoricalVerificationBlockerLine,
    publicMergeReadinessBlock,
    publicRankScaleLine,
    publicRealBehaviorProofLine,
    publicReviewScoresBlock,
    publicReviewTextDiffers,
    publicReviewTextIsSame,
    publicRiskBullets,
    publicSecurityReviewLine,
    pullHeadShaFromContext,
    pullHeadShaFromReport,
    renderOpenClawPrSurfaceFromReport,
    renderReviewMetricsDigest,
    repairLoopPassModeFromReport,
    replaceFrontMatterValue,
    repoRelativePath,
    reportAgentsPolicyStatus,
    reportEvidence,
    reportLikelyOwners,
    reportLiveProofRecordingBlock,
    reportOverallConfidenceScore,
    reportOverallCorrectness,
    reportPrRating,
    reportRealBehaviorProofPolicy,
    reportReviewFindings,
    reportRootCauseCluster,
    reportRiskEntries,
    reportSecurityReview,
    reviewAutomationMarkersFromReport,
    reviewFindingDetailedLine,
    reviewFindingLocation,
    reviewFindingSummaryLine,
    reviewMetricsFromReport,
    reviewSectionValue,
    reviewStructuralPullStateFromContext,
    reviewVersionMarkerFromReport,
    ROOT,
    sanitizeArchitectureDiagram,
    securityConcernDetailedLine,
    securityConcernLocation,
    securityConcernSummaryLine,
    securityReviewLine,
    sentence,
    sha256,
    shouldRenderWorkPlanFromReport,
    stripListMarker,
    targetRepo,
    timestampMs,
    triagePriorityFromReport,
    validateCloseDecision,
    workCandidateReasonText,
    workPlanPathForReport,
    workStatusForDecision,
  });
  const {
    OWNED_REVIEW_SECTION_HEADINGS,
    closeItem,
    currentReviewRevision,
    markdownFor,
    pullRequestFilePathsFromContextForTest,
    pullRequestHeadSha,
    pullRequestReviewReadinessFromReport,
    renderReviewCommentFromReport,
    renderReviewContextBudgetForTest,
    renderWorkPlanFromReport,
    reviewActionForDecision,
    reviewContextLedgerForTest,
    reviewHistoryForStaleComment,
    securitySensitiveRepairAllowed,
    syncWorkPlanFromReport,
    updateReviewStructuralFrontMatter,
  } = reportRendering;

  return {
    OWNED_REVIEW_SECTION_HEADINGS,
    applyAuthorPrBudgetStateToReport,
    applyClosedUnmergedCanonicalBlockedReport,
    applyPrCloseCoverageProofBlockedReport,
    applyPrCloseCoverageProofReportSection,
    authorPrBudgetPromotion,
    canonicalPullRequestCommentSyncBlock,
    closeItem,
    completeStaleCanonicalCommentSyncReport,
    contextHasNonAutomationActivityAfter,
    contextHasNonAutomationActivityAfterForTest,
    coveringPrCloseCoveragePullRequestSnapshotSha256,
    currentReviewRevision,
    duplicateCanonicalPullRequestBlockReason,
    hasNormalizedLabel,
    impactLabelSchemeForTest,
    impactLabelsForTest,
    isClawSweeperOwnedLabel,
    isGitHubLabelAlreadyExistsErrorForTest,
    isGitHubLabelCapacityErrorForTest,
    isMissingGitHubLabelErrorForTest,
    issueAdvisoryLabelsForTest,
    labelJustificationsMarkdownForTest,
    labelSynchronization,
    livePullRequestHasNoDiff,
    markdownFor,
    maturityLabelSchemeForTest,
    maturityLabelsForTest,
    mergeRiskLabelSchemeForTest,
    mergeRiskLabelsForTest,
    normalizedLabelSet,
    parseBacktickLocation,
    prCloseCoverageProofGateResult,
    prRatingLabelSchemeForTest,
    prRatingLabelsForTest,
    priorityLabelSchemeForTest,
    priorityLabelsForTest,
    pullRequestClosePromotion,
    pullRequestFilePathsFromContextForTest,
    pullRequestHeadSha,
    pullRequestReviewReadinessFromReport,
    realBehaviorProofBlocksMerge,
    realBehaviorProofMediaLabelsForTest,
    realBehaviorProofSufficientLabelsForTest,
    renderReviewCommentFromReport,
    renderReviewContextBudgetForTest,
    renderWorkPlanFromReport,
    reportDecision,
    reviewActionForDecision,
    reviewContextLedgerForTest,
    reviewHistoryForStaleComment,
    securitySensitiveRepairAllowed,
    staleCanonicalCommentSyncPendingReason,
    staleCanonicalPullRequestNumber,
    syncBulkFilerLabelForTest,
    syncWorkPlanFromReport,
    telegramVisibleProofLabelsForTest,
    updateReviewStructuralFrontMatter,
    upgradeNoDiffPullRequestReport,
    upgradePullRequestClosePromotionReport,
    workPlanPathForReport,
  };
}
